// flow-typed signature: 50262bcf8924d126d28c62927a5a7199
// flow-typed version: <<STUB>>/@lugia/mega-jest_v^1.2.27/flow_v0.99.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lugia/mega-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lugia/mega-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@lugia/mega-jest/bin/mega-jest' {
  declare module.exports: any;
}

declare module '@lugia/mega-jest/lib/fileTransform' {
  declare module.exports: any;
}

declare module '@lugia/mega-jest/lib/index' {
  declare module.exports: any;
}

declare module '@lugia/mega-jest/lib/jasmine' {
  declare module.exports: any;
}

declare module '@lugia/mega-jest/lib/jsTransformer' {
  declare module.exports: any;
}

declare module '@lugia/mega-jest/lib/setupTests' {
  declare module.exports: any;
}

declare module '@lugia/mega-jest/lib/shim' {
  declare module.exports: any;
}

declare module '@lugia/mega-jest/lib/styleMock' {
  declare module.exports: any;
}

declare module '@lugia/mega-jest/lib/tsTransformer' {
  declare module.exports: any;
}

// Filename aliases
declare module '@lugia/mega-jest/bin/mega-jest.js' {
  declare module.exports: $Exports<'@lugia/mega-jest/bin/mega-jest'>;
}
declare module '@lugia/mega-jest/lib/fileTransform.js' {
  declare module.exports: $Exports<'@lugia/mega-jest/lib/fileTransform'>;
}
declare module '@lugia/mega-jest/lib/index.js' {
  declare module.exports: $Exports<'@lugia/mega-jest/lib/index'>;
}
declare module '@lugia/mega-jest/lib/jasmine.js' {
  declare module.exports: $Exports<'@lugia/mega-jest/lib/jasmine'>;
}
declare module '@lugia/mega-jest/lib/jsTransformer.js' {
  declare module.exports: $Exports<'@lugia/mega-jest/lib/jsTransformer'>;
}
declare module '@lugia/mega-jest/lib/setupTests.js' {
  declare module.exports: $Exports<'@lugia/mega-jest/lib/setupTests'>;
}
declare module '@lugia/mega-jest/lib/shim.js' {
  declare module.exports: $Exports<'@lugia/mega-jest/lib/shim'>;
}
declare module '@lugia/mega-jest/lib/styleMock.js' {
  declare module.exports: $Exports<'@lugia/mega-jest/lib/styleMock'>;
}
declare module '@lugia/mega-jest/lib/tsTransformer.js' {
  declare module.exports: $Exports<'@lugia/mega-jest/lib/tsTransformer'>;
}
