// flow-typed signature: 3113ed6ce4d29866fc0acdf5907bf537
// flow-typed version: <<STUB>>/@lugia/mega_v^1.3.44/flow_v0.99.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lugia/mega'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lugia/mega' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@lugia/mega/bin/mega-build' {
  declare module.exports: any;
}

declare module '@lugia/mega/bin/mega-create' {
  declare module.exports: any;
}

declare module '@lugia/mega/bin/mega-generate' {
  declare module.exports: any;
}

declare module '@lugia/mega/bin/mega-serve' {
  declare module.exports: any;
}

declare module '@lugia/mega/bin/mega' {
  declare module.exports: any;
}

declare module '@lugia/mega/lib/create' {
  declare module.exports: any;
}

declare module '@lugia/mega/lib/generate' {
  declare module.exports: any;
}

declare module '@lugia/mega/lib/getDefaultEntry' {
  declare module.exports: any;
}

declare module '@lugia/mega/lib/getPlugins' {
  declare module.exports: any;
}

declare module '@lugia/mega/lib/install' {
  declare module.exports: any;
}

declare module '@lugia/mega/lib/localScaffolding' {
  declare module.exports: any;
}

declare module '@lugia/mega/lib/missingArgument' {
  declare module.exports: any;
}

declare module '@lugia/mega/lib/pageGenerate' {
  declare module.exports: any;
}

declare module '@lugia/mega/lib/singleBuild' {
  declare module.exports: any;
}

declare module '@lugia/mega/lib/singleServe' {
  declare module.exports: any;
}

declare module '@lugia/mega/lib/tryGitInit' {
  declare module.exports: any;
}

declare module '@lugia/mega/scaffolding/lugia.config' {
  declare module.exports: any;
}

declare module '@lugia/mega/scaffolding/meta' {
  declare module.exports: any;
}

declare module '@lugia/mega/scaffolding/mock.config' {
  declare module.exports: any;
}

declare module '@lugia/mega/scaffolding/mock/random' {
  declare module.exports: any;
}

declare module '@lugia/mega/scaffolding/src/App/App' {
  declare module.exports: any;
}

declare module '@lugia/mega/scaffolding/src/App/index' {
  declare module.exports: any;
}

declare module '@lugia/mega/scaffolding/src/index' {
  declare module.exports: any;
}

declare module '@lugia/mega/scaffolding/src/registerServiceWorker' {
  declare module.exports: any;
}

declare module '@lugia/mega/scaffolding/test/a.test' {
  declare module.exports: any;
}

declare module '@lugia/mega/scaffolding/test/App.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@lugia/mega/bin/mega-build.js' {
  declare module.exports: $Exports<'@lugia/mega/bin/mega-build'>;
}
declare module '@lugia/mega/bin/mega-create.js' {
  declare module.exports: $Exports<'@lugia/mega/bin/mega-create'>;
}
declare module '@lugia/mega/bin/mega-generate.js' {
  declare module.exports: $Exports<'@lugia/mega/bin/mega-generate'>;
}
declare module '@lugia/mega/bin/mega-serve.js' {
  declare module.exports: $Exports<'@lugia/mega/bin/mega-serve'>;
}
declare module '@lugia/mega/bin/mega.js' {
  declare module.exports: $Exports<'@lugia/mega/bin/mega'>;
}
declare module '@lugia/mega/lib/create.js' {
  declare module.exports: $Exports<'@lugia/mega/lib/create'>;
}
declare module '@lugia/mega/lib/generate.js' {
  declare module.exports: $Exports<'@lugia/mega/lib/generate'>;
}
declare module '@lugia/mega/lib/getDefaultEntry.js' {
  declare module.exports: $Exports<'@lugia/mega/lib/getDefaultEntry'>;
}
declare module '@lugia/mega/lib/getPlugins.js' {
  declare module.exports: $Exports<'@lugia/mega/lib/getPlugins'>;
}
declare module '@lugia/mega/lib/install.js' {
  declare module.exports: $Exports<'@lugia/mega/lib/install'>;
}
declare module '@lugia/mega/lib/localScaffolding.js' {
  declare module.exports: $Exports<'@lugia/mega/lib/localScaffolding'>;
}
declare module '@lugia/mega/lib/missingArgument.js' {
  declare module.exports: $Exports<'@lugia/mega/lib/missingArgument'>;
}
declare module '@lugia/mega/lib/pageGenerate.js' {
  declare module.exports: $Exports<'@lugia/mega/lib/pageGenerate'>;
}
declare module '@lugia/mega/lib/singleBuild.js' {
  declare module.exports: $Exports<'@lugia/mega/lib/singleBuild'>;
}
declare module '@lugia/mega/lib/singleServe.js' {
  declare module.exports: $Exports<'@lugia/mega/lib/singleServe'>;
}
declare module '@lugia/mega/lib/tryGitInit.js' {
  declare module.exports: $Exports<'@lugia/mega/lib/tryGitInit'>;
}
declare module '@lugia/mega/scaffolding/lugia.config.js' {
  declare module.exports: $Exports<'@lugia/mega/scaffolding/lugia.config'>;
}
declare module '@lugia/mega/scaffolding/meta.js' {
  declare module.exports: $Exports<'@lugia/mega/scaffolding/meta'>;
}
declare module '@lugia/mega/scaffolding/mock.config.js' {
  declare module.exports: $Exports<'@lugia/mega/scaffolding/mock.config'>;
}
declare module '@lugia/mega/scaffolding/mock/random.js' {
  declare module.exports: $Exports<'@lugia/mega/scaffolding/mock/random'>;
}
declare module '@lugia/mega/scaffolding/src/App/App.jsx' {
  declare module.exports: $Exports<'@lugia/mega/scaffolding/src/App/App'>;
}
declare module '@lugia/mega/scaffolding/src/App/index.js' {
  declare module.exports: $Exports<'@lugia/mega/scaffolding/src/App/index'>;
}
declare module '@lugia/mega/scaffolding/src/index.js' {
  declare module.exports: $Exports<'@lugia/mega/scaffolding/src/index'>;
}
declare module '@lugia/mega/scaffolding/src/registerServiceWorker.js' {
  declare module.exports: $Exports<
    '@lugia/mega/scaffolding/src/registerServiceWorker',
  >;
}
declare module '@lugia/mega/scaffolding/test/a.test.js' {
  declare module.exports: $Exports<'@lugia/mega/scaffolding/test/a.test'>;
}
declare module '@lugia/mega/scaffolding/test/App.test.js' {
  declare module.exports: $Exports<'@lugia/mega/scaffolding/test/App.test'>;
}
