// flow-typed signature: a425445083e5ce6dfdbe7713170cf485
// flow-typed version: <<STUB>>/@lugia/react-devtools-core_v1.0.0/flow_v0.99.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lugia/react-devtools-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lugia/react-devtools-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@lugia/react-devtools-core/build/backend' {
  declare module.exports: any;
}

// Filename aliases
declare module '@lugia/react-devtools-core/build/backend.js' {
  declare module.exports: $Exports<'@lugia/react-devtools-core/build/backend'>;
}
