// flow-typed signature: d8d8a5a613c12b3faf32a44952699fcd
// flow-typed version: <<STUB>>/deepmerge_v3.2.0/flow_v0.99.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'deepmerge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'deepmerge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'deepmerge/dist/umd' {
  declare module.exports: any;
}

declare module 'deepmerge/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'deepmerge/dist/umd.js' {
  declare module.exports: $Exports<'deepmerge/dist/umd'>;
}
declare module 'deepmerge/index' {
  declare module.exports: $Exports<'deepmerge'>;
}
declare module 'deepmerge/index.js' {
  declare module.exports: $Exports<'deepmerge'>;
}
declare module 'deepmerge/rollup.config.js' {
  declare module.exports: $Exports<'deepmerge/rollup.config'>;
}
