// flow-typed signature: bfef9c1e4104bf6d2270438b79f60ad1
// flow-typed version: <<STUB>>/slash_v^3.0.0/flow_v0.99.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'slash/index' {
  declare module.exports: $Exports<'slash'>;
}
declare module 'slash/index.js' {
  declare module.exports: $Exports<'slash'>;
}
