// flow-typed signature: 1564e249db4893d924f1ce5f1be3074d
// flow-typed version: <<STUB>>/@babel/preset-react_v^7.0.0/flow_v0.99.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/preset-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/preset-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/preset-react/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/preset-react/lib/index.js' {
  declare module.exports: $Exports<'@babel/preset-react/lib/index'>;
}
