export default {
  colors: [
    {
      chineseName: '成功色',
      englishName: 'success',
      Hex: '#56c22d',
      RGB: 'rgb(86,194,45)',
    },
    {
      chineseName: '警告色',
      englishName: 'warning',
      Hex: '#f8ac30',
      RGB: 'rgb(248,172,48)',
    },
    {
      chineseName: '危险色',
      englishName: 'danger',
      Hex: '#f22735',
      RGB: 'rgb(242,39,53)',
    },
    {
      chineseName: '浅粉红',
      englishName: 'LightPink',
      Hex: '#FFB6C1',
      RGB: 'rgb(255,182,193)',
    },
    {
      chineseName: '粉红',
      englishName: 'Pink',
      Hex: '#FFC0CB',
      RGB: 'rgb(255,192,203)',
    },
    {
      chineseName: '猩红',
      englishName: 'Crimson',
      Hex: '#DC143C',
      RGB: 'rgb(220,20,60)',
    },
    {
      chineseName: '脸红的淡紫色',
      englishName: 'LavenderBlush',
      Hex: '#FFF0F5',
      RGB: 'rgb(255,240,245)',
    },
    {
      chineseName: '苍白的紫罗兰红色',
      englishName: 'PaleVioletRed',
      Hex: '#DB7093',
      RGB: 'rgb(219,112,147)',
    },
    {
      chineseName: '热情的粉红',
      englishName: 'HotPink',
      Hex: '#FF69B4',
      RGB: 'rgb(255,105,180)',
    },
    {
      chineseName: '深粉色',
      englishName: 'DeepPink',
      Hex: '#FF1493',
      RGB: 'rgb(255,20,147)',
    },
    {
      chineseName: '适中的紫罗兰红色',
      englishName: 'MediumVioletRed',
      Hex: '#C71585',
      RGB: 'rgb(199,21,133)',
    },
    {
      chineseName: '兰花的紫色',
      englishName: 'Orchid',
      Hex: '#DA70D6',
      RGB: 'rgb(218,112,214)',
    },
    {
      chineseName: '蓟',
      englishName: 'Thistle',
      Hex: '#D8BFD8',
      RGB: 'rgb(216,191,216)',
    },
    {
      chineseName: '李子',
      englishName: 'plum',
      Hex: '#DDA0DD',
      RGB: 'rgb(221,160,221)',
    },
    {
      chineseName: '紫罗兰',
      englishName: 'Violet',
      Hex: '#EE82EE',
      RGB: 'rgb(238,130,238)',
    },
    {
      chineseName: '洋红',
      englishName: 'Magenta',
      Hex: '#FF00FF',
      RGB: 'rgb(255,0,255)',
    },
    {
      chineseName: '灯笼海棠(紫红色)',
      englishName: 'Fuchsia',
      Hex: '#FF00FF',
      RGB: 'rgb(255,0,255)',
    },
    {
      chineseName: '深洋红色',
      englishName: 'DarkMagenta',
      Hex: '#8B008B',
      RGB: 'rgb(139,0,139)',
    },
    {
      chineseName: '深洋红色',
      englishName: 'DarkMagenta',
      Hex: '#8B008B',
      RGB: 'rgb(139,0,139)',
    },
    {
      chineseName: '紫色',
      englishName: 'Purple',
      Hex: '#800080',
      RGB: 'rgb(128,0,128)',
    },
    {
      chineseName: '适中的兰花紫',
      englishName: 'MediumOrchid',
      Hex: '#BA55D3',
      RGB: 'rgb(186,85,211)',
    },
    {
      chineseName: '深紫罗兰色',
      englishName: 'DarkVoilet',
      Hex: '#9400D3',
      RGB: 'rgb(148,0,211)',
    },
    {
      chineseName: '深兰花紫',
      englishName: 'DarkOrchid',
      Hex: '#9932CC',
      RGB: 'rgb(153,50,204)',
    },
    {
      chineseName: '靛青',
      englishName: 'Indigo',
      Hex: '#4B0082',
      RGB: 'rgb(75,0,130)',
    },
    {
      chineseName: '深紫罗兰的蓝色',
      englishName: 'BlueViolet',
      Hex: '#8A2BE2',
      RGB: 'rgb(138,43,226)',
    },
    {
      chineseName: '适中的紫色',
      englishName: 'MediumPurple',
      Hex: '#9370DB',
      RGB: 'rgb(147,112,219)',
    },
    {
      chineseName: '适中的板岩暗蓝灰色',
      englishName: 'MediumSlateBlue',
      Hex: '#7B68EE',
      RGB: 'rgb(123,104,238)',
    },
    {
      chineseName: '板岩暗蓝灰色',
      englishName: 'SlateBlue',
      Hex: '#6A5ACD',
      RGB: 'rgb(106,90,205)',
    },
    {
      chineseName: '深岩暗蓝灰色',
      englishName: 'DarkSlateBlue',
      Hex: '#483D8B',
      RGB: 'rgb(72,61,139)',
    },
    {
      chineseName: '熏衣草花的淡紫色',
      englishName: 'Lavender',
      Hex: '#E6E6FA',
      RGB: 'rgb(230,230,250)',
    },
    {
      chineseName: '幽灵的白色',
      englishName: 'GhostWhite',
      Hex: '#F8F8FF',
      RGB: 'rgb(248,248,255)',
    },
    {
      chineseName: '纯蓝',
      englishName: 'Blue',
      Hex: '#0000FF',
      RGB: 'rgb(0,0,255)',
    },
    {
      chineseName: '适中的蓝色',
      englishName: 'MediumBlue',
      Hex: '#0000CD',
      RGB: 'rgb(0,0,205)',
    },
    {
      chineseName: '午夜的蓝色',
      englishName: 'MidnightBlue',
      Hex: '#191970',
      RGB: 'rgb(25,25,112)',
    },
    {
      chineseName: '深蓝色',
      englishName: 'DarkBlue',
      Hex: '#00008B',
      RGB: 'rgb(0,0,139)',
    },
    {
      chineseName: '海军蓝',
      englishName: 'Navy',
      Hex: '#000080',
      RGB: 'rgb(0,0,128)',
    },
    {
      chineseName: '皇军蓝',
      englishName: 'RoyalBlue',
      Hex: '#4169E1',
      RGB: 'rgb(65,105,225)',
    },
    {
      chineseName: '矢车菊的蓝色',
      englishName: 'CornflowerBlue',
      Hex: '#6495ED',
      RGB: 'rgb(100,149,237)',
    },
    {
      chineseName: '淡钢蓝',
      englishName: 'LightSteelBlue',
      Hex: '#B0C4DE',
      RGB: 'rgb(176,196,222)',
    },
    {
      chineseName: '浅石板灰',
      englishName: 'LightSlateGray',
      Hex: '#778899',
      RGB: 'rgb(119,136,153)',
    },
    {
      chineseName: '石板灰',
      englishName: 'SlateGray',
      Hex: '#708090',
      RGB: 'rgb(112,128,144)',
    },
    {
      chineseName: '道奇蓝',
      englishName: 'DoderBlue',
      Hex: '#1E90FF',
      RGB: 'rgb(30,144,255)',
    },
    {
      chineseName: '爱丽丝蓝',
      englishName: 'AliceBlue',
      Hex: '#F0F8FF',
      RGB: 'rgb(240,248,255)',
    },
    {
      chineseName: '钢蓝',
      englishName: 'SteelBlue',
      Hex: '#4682B4',
      RGB: 'rgb(70,130,180)',
    },
    {
      chineseName: '淡蓝色',
      englishName: 'LightSkyBlue',
      Hex: '#87CEFA',
      RGB: 'rgb(135,206,250)',
    },
    {
      chineseName: '天蓝色',
      englishName: 'SkyBlue',
      Hex: '#87CEEB',
      RGB: 'rgb(135,206,235)',
    },
    {
      chineseName: '深天蓝',
      englishName: 'DeepSkyBlue',
      Hex: '#00BFFF',
      RGB: 'rgb(0,191,255)',
    },
    {
      chineseName: '淡蓝',
      englishName: 'LightBLue',
      Hex: '#ADD8E6',
      RGB: 'rgb(173,216,230)',
    },
    {
      chineseName: '火药蓝',
      englishName: 'PowDerBlue',
      Hex: '#B0E0E6',
      RGB: 'rgb(176,224,230)',
    },
    {
      chineseName: '军校蓝',
      englishName: 'CadetBlue',
      Hex: '#5F9EA0',
      RGB: 'rgb(95,158,160)',
    },
    {
      chineseName: '蔚蓝色',
      englishName: 'Azure',
      Hex: '#F0FFFF',
      RGB: 'rgb(240,255,255)',
    },
    {
      chineseName: '淡青色',
      englishName: 'LightCyan',
      Hex: '#E1FFFF',
      RGB: 'rgb(225,255,255)',
    },
    {
      chineseName: '苍白的绿宝石',
      englishName: 'PaleTurquoise',
      Hex: '#AFEEEE',
      RGB: 'rgb(175,238,238)',
    },
    {
      chineseName: '青色',
      englishName: 'Cyan',
      Hex: '#00FFFF',
      RGB: 'rgb(0,255,255)',
    },
    {
      chineseName: '水绿色',
      englishName: 'Aqua',
      Hex: '#00FFFF',
      RGB: 'rgb(0,255,255)',
    },
    {
      chineseName: '深绿宝石',
      englishName: 'DarkTurquoise',
      Hex: '#00CED1',
      RGB: 'rgb(0,206,209)',
    },
    {
      chineseName: '深石板灰',
      englishName: 'DarkSlateGray',
      Hex: '#2F4F4F',
      RGB: 'rgb(47,79,79)',
    },
    {
      chineseName: '深青色',
      englishName: 'DarkCyan',
      Hex: '#008B8B',
      RGB: 'rgb(0,139,139)',
    },
    {
      chineseName: '水鸭色',
      englishName: 'Teal',
      Hex: '#008080',
      RGB: 'rgb(0,128,128)',
    },
    {
      chineseName: '适中的绿宝石',
      englishName: 'MediumTurquoise',
      Hex: '#48D1CC',
      RGB: 'rgb(72,209,204)',
    },
    {
      chineseName: '浅海洋绿',
      englishName: 'LightSeaGreen',
      Hex: '#20B2AA',
      RGB: 'rgb(32,178,170)',
    },
    {
      chineseName: '绿宝石',
      englishName: 'Turquoise',
      Hex: '#40E0D0',
      RGB: 'rgb(64,224,208)',
    },
    {
      chineseName: '绿玉|碧绿色',
      englishName: 'Auqamarin',
      Hex: '#7FFFAA',
      RGB: 'rgb(127,255,170)',
    },
    {
      chineseName: '适中的碧绿色',
      englishName: 'MediumAquamarine',
      Hex: '#00FA9A',
      RGB: 'rgb(0,250,154)',
    },
    {
      chineseName: '适中的春天的绿色',
      englishName: 'MediumSpringGreen',
      Hex: '#F5FFFA',
      RGB: 'rgb(245,255,250)',
    },
    {
      chineseName: '薄荷奶油',
      englishName: 'MintCream',
      Hex: '#00FF7F',
      RGB: 'rgb(0,255,127)',
    },
    {
      chineseName: '春天的绿色',
      englishName: 'SpringGreen',
      Hex: '#3CB371',
      RGB: 'rgb(60,179,113)',
    },
    {
      chineseName: '海洋绿',
      englishName: 'SeaGreen',
      Hex: '#2E8B57',
      RGB: 'rgb(46,139,87)',
    },
    {
      chineseName: '蜂蜜',
      englishName: 'Honeydew',
      Hex: '#F0FFF0',
      RGB: 'rgb(240,255,240)',
    },
    {
      chineseName: '淡绿色',
      englishName: 'LightGreen',
      Hex: '#90EE90',
      RGB: 'rgb(144,238,144)',
    },
    {
      chineseName: '苍白的绿色',
      englishName: 'PaleGreen',
      Hex: '#98FB98',
      RGB: 'rgb(152,251,152)',
    },
    {
      chineseName: '深海洋绿',
      englishName: 'DarkSeaGreen',
      Hex: '#8FBC8F',
      RGB: 'rgb(143,188,143)',
    },
    {
      chineseName: '酸橙绿',
      englishName: 'LimeGreen',
      Hex: '#32CD32',
      RGB: 'rgb(50,205,50)',
    },
    {
      chineseName: '酸橙色',
      englishName: 'Lime',
      Hex: '#00FF00',
      RGB: 'rgb(0,255,0)',
    },
    {
      chineseName: '森林绿',
      englishName: 'ForestGreen',
      Hex: '#228B22',
      RGB: 'rgb(34,139,34)',
    },
    {
      chineseName: '纯绿',
      englishName: 'Green',
      Hex: '#008000',
      RGB: 'rgb(0,128,0)',
    },
    {
      chineseName: '深绿色',
      englishName: 'DarkGreen',
      Hex: '#006400',
      RGB: 'rgb(0,100,0)',
    },
    {
      chineseName: '查特酒绿',
      englishName: 'Chartreuse',
      Hex: '#7FFF00',
      RGB: 'rgb(127,255,0)',
    },
    {
      chineseName: '草坪绿',
      englishName: 'LawnGreen',
      Hex: '#7CFC00',
      RGB: 'rgb(124,252,0)',
    },
    {
      chineseName: '绿黄色',
      englishName: 'GreenYellow',
      Hex: '#ADFF2F',
      RGB: 'rgb(173,255,47)',
    },
    {
      chineseName: '橄榄土褐色',
      englishName: 'OliveDrab',
      Hex: '#556B2F',
      RGB: 'rgb(85,107,47)',
    },
    {
      chineseName: '米色(浅褐色)',
      englishName: 'Beige',
      Hex: '#6B8E23',
      RGB: 'rgb(107,142,35)',
    },
    {
      chineseName: '浅秋麒麟黄',
      englishName: 'LightGoldenrodYellow',
      Hex: '#FAFAD2',
      RGB: 'rgb(250,250,210)',
    },
    {
      chineseName: '象牙',
      englishName: 'Ivory',
      Hex: '#FFFFF0',
      RGB: 'rgb(255,255,240)',
    },
    {
      chineseName: '浅黄色',
      englishName: 'LightYellow',
      Hex: '#FFFFE0',
      RGB: 'rgb(255,255,224)',
    },
    {
      chineseName: '纯黄',
      englishName: 'Yellow',
      Hex: '#FFFF00',
      RGB: 'rgb(255,255,0)',
    },
    {
      chineseName: '橄榄',
      englishName: 'Olive',
      Hex: '#808000',
      RGB: 'rgb(128,128,0)',
    },
    {
      chineseName: '深卡其布',
      englishName: 'DarkKhaki',
      Hex: '#BDB76B',
      RGB: 'rgb(189,183,107)',
    },
    {
      chineseName: '柠檬薄纱',
      englishName: 'LemonChiffon',
      Hex: '#FFFACD',
      RGB: 'rgb(255,250,205)',
    },
    {
      chineseName: '灰秋麒麟',
      englishName: 'PaleGodenrod',
      Hex: '#EEE8AA',
      RGB: 'rgb(238,232,170)',
    },
    {
      chineseName: '卡其布',
      englishName: 'Khaki',
      Hex: '#F0E68C',
      RGB: 'rgb(240,230,140)',
    },
    {
      chineseName: '金',
      englishName: 'Gold',
      Hex: '#FFD700',
      RGB: 'rgb(255,215,0)',
    },
    {
      chineseName: '玉米色',
      englishName: 'Cornislk',
      Hex: '#FFF8DC',
      RGB: 'rgb(255,248,220)',
    },
    {
      chineseName: '秋麒麟',
      englishName: 'GoldEnrod',
      Hex: '#DAA520',
      RGB: 'rgb(218,165,32)',
    },
    {
      chineseName: '花的白色',
      englishName: 'FloralWhite',
      Hex: '#FFFAF0',
      RGB: 'rgb(255,250,240)',
    },
    {
      chineseName: '老饰带',
      englishName: 'OldLace',
      Hex: '#FDF5E6',
      RGB: 'rgb(253,245,230)',
    },
    {
      chineseName: '小麦色',
      englishName: 'Wheat',
      Hex: '#F5DEB3',
      RGB: 'rgb(245,222,179)',
    },
    {
      chineseName: '鹿皮鞋',
      englishName: 'Moccasin',
      Hex: '#FFE4B5',
      RGB: 'rgb(255,228,181)',
    },
    {
      chineseName: '橙色',
      englishName: 'Orange',
      Hex: '#FFA500',
      RGB: 'rgb(255,165,0)',
    },
    {
      chineseName: '番木瓜',
      englishName: 'PapayaWhip',
      Hex: '#FFEFD5',
      RGB: 'rgb(255,239,213)',
    },
    {
      chineseName: '漂白的杏仁',
      englishName: 'BlanchedAlmond',
      Hex: '#FFEBCD',
      RGB: 'rgb(255,235,205)',
    },
    {
      chineseName: 'Navajo白',
      englishName: 'NavajoWhite',
      Hex: '#FFDEAD',
      RGB: 'rgb(255,222,173)',
    },
    {
      chineseName: '古代的白色',
      englishName: 'AntiqueWhite',
      Hex: '#FAEBD7',
      RGB: 'rgb(250,235,215)',
    },
    {
      chineseName: '晒黑',
      englishName: 'Tan',
      Hex: '#D2B48C',
      RGB: 'rgb(210,180,140)',
    },
    {
      chineseName: '结实的树',
      englishName: 'BrulyWood',
      Hex: '#DEB887',
      RGB: 'rgb(222,184,135)',
    },
    {
      chineseName: '(浓汤)乳脂,番茄等',
      englishName: 'Bisque',
      Hex: '#FFE4C4',
      RGB: 'rgb(255,228,196)',
    },
    {
      chineseName: '深橙色',
      englishName: 'DarkOrange',
      Hex: '#FF8C00',
      RGB: 'rgb(255,140,0)',
    },
    {
      chineseName: '亚麻布',
      englishName: 'Linen',
      Hex: '#FAF0E6',
      RGB: 'rgb(250,240,230)',
    },
    {
      chineseName: '秘鲁',
      englishName: 'Peru',
      Hex: '#CD853F',
      RGB: 'rgb(205,133,63)',
    },
    {
      chineseName: '桃色',
      englishName: 'PeachPuff',
      Hex: '#FFDAB9',
      RGB: 'rgb(255,218,185)',
    },
    {
      chineseName: '沙棕色',
      englishName: 'SandyBrown',
      Hex: '#F4A460',
      RGB: 'rgb(244,164,96)',
    },
    {
      chineseName: '巧克力',
      englishName: 'Chocolate',
      Hex: '#D2691E',
      RGB: 'rgb(210,105,30)',
    },
    {
      chineseName: '马鞍棕色',
      englishName: 'SaddleBrown',
      Hex: '#8B4513',
      RGB: 'rgb(139,69,19)',
    },
    {
      chineseName: '海贝壳',
      englishName: 'SeaShell',
      Hex: '#FFF5EE',
      RGB: 'rgb(255,245,238)',
    },
    {
      chineseName: '黄土赭色',
      englishName: 'Sienna',
      Hex: '#A0522D',
      RGB: 'rgb(160,82,45)',
    },
    {
      chineseName: '浅鲜肉(鲑鱼)色',
      englishName: 'LightSalmon',
      Hex: '#FFA07A',
      RGB: 'rgb(255,160,122)',
    },
    {
      chineseName: '珊瑚',
      englishName: 'Coral',
      Hex: '#FF7F50',
      RGB: 'rgb(255,127,80)',
    },
    {
      chineseName: '橙红色',
      englishName: 'OrangeRed',
      Hex: '#FF4500',
      RGB: 'rgb(255,69,0)',
    },
    {
      chineseName: '深鲜肉(鲑鱼)色',
      englishName: 'DarkSalmon',
      Hex: '#E9967A',
      RGB: 'rgb(233,150,122)',
    },
    {
      chineseName: '番茄',
      englishName: 'Tomato',
      Hex: '#FF6347',
      RGB: 'rgb(255,99,71)',
    },
    {
      chineseName: '薄雾玫瑰',
      englishName: 'MistyRose',
      Hex: '#FFE4E1',
      RGB: 'rgb(255,228,225)',
    },
    {
      chineseName: '鲜肉(鲑鱼)色',
      englishName: 'Salmon',
      Hex: '#FA8072',
      RGB: 'rgb(250,128,114)',
    },
    {
      chineseName: '雪',
      englishName: 'Snow',
      Hex: '#FFFAFA',
      RGB: 'rgb(255,250,250)',
    },
    {
      chineseName: '淡珊瑚色',
      englishName: 'LightCoral',
      Hex: '#F08080',
      RGB: 'rgb(240,128,128)',
    },
    {
      chineseName: '玫瑰棕色',
      englishName: 'RosyBrown',
      Hex: '#BC8F8F',
      RGB: 'rgb(188,143,143)',
    },
    {
      chineseName: '印度红',
      englishName: 'IndianRed',
      Hex: '#CD5C5C',
      RGB: 'rgb(205,92,92)',
    },
    {
      chineseName: '纯红',
      englishName: 'Red',
      Hex: '#FF0000',
      RGB: 'rgb(255,0,0)',
    },
    {
      chineseName: '棕色',
      englishName: 'Brown',
      Hex: '#A52A2A',
      RGB: 'rgb(165,42,42)',
    },
    {
      chineseName: '耐火砖',
      englishName: 'FireBrick',
      Hex: '#B22222',
      RGB: 'rgb(178,34,34)',
    },
    {
      chineseName: '深红色',
      englishName: 'DarkRed',
      Hex: '#8B0000',
      RGB: 'rgb(139,0,0)',
    },
    {
      chineseName: '栗色',
      englishName: 'Maroon',
      Hex: '#800000',
      RGB: 'rgb(128,0,0)',
    },
    {
      chineseName: '纯白',
      englishName: 'White',
      Hex: '#FFFFFF',
      RGB: 'rgb(255,255,255)',
    },
    {
      chineseName: '白烟',
      englishName: 'WhiteSmoke',
      Hex: '#F5F5F5',
      RGB: 'rgb(245,245,245)',
    },
    {
      chineseName: 'Gainsboro',
      englishName: 'Gainsboro',
      Hex: '#DCDCDC',
      RGB: 'rgb(220,220,220)',
    },
    {
      chineseName: '浅灰色',
      englishName: 'LightGrey',
      Hex: '#D3D3D3',
      RGB: 'rgb(211,211,211)',
    },
    {
      chineseName: '银白色',
      englishName: 'Silver',
      Hex: '#C0C0C0',
      RGB: 'rgb(192,192,192)',
    },
    {
      chineseName: '深灰色',
      englishName: 'DarkGray',
      Hex: '#A9A9A9',
      RGB: 'rgb(169,169,169)',
    },
    {
      chineseName: '灰色',
      englishName: 'Gray',
      Hex: '#808080',
      RGB: 'rgb(128,128,128)',
    },
    {
      chineseName: '暗淡的灰色',
      englishName: 'DimGray',
      Hex: '#696969',
      RGB: 'rgb(105,105,105)',
    },
    {
      chineseName: '纯黑',
      englishName: 'Black',
      Hex: '#000000',
      RGB: 'rgb(0,0,0)',
    },
  ],
};
